version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./web-dashboard/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
    volumes:
      - ./web-dashboard/backend:/app
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - wild-analytics

  # Frontend
  frontend:
    build:
      context: ./wild-analytics-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_ENVIRONMENT=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - wild-analytics

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - wild-analytics

networks:
  wild-analytics:
    driver: bridge 